[recipe] mul_cn and unified char and bpe data format
mobvoi/wenet pull request #210
Opened 2021-03-13 06:05 UTC by whiteshirt0429

2021-03-15 01:40 UTC, robin1001 commented on examples/multi_cn/s0/run.sh
> +# Author: di.wu@mobvoi.com (DI WU)
Copyright 2021 Mobvoi Inc. All Rights Reserved. (Di Wu)

2021-03-15 01:45 UTC, robin1001 commented on examples/multi_cn/s0/run.sh
> +bpecode=../../librispeech/s0/data/lang_char/train_960_unigram5000.model
呃 what's this? it shouldn't be here.

2021-03-15 01:47 UTC, robin1001 commented on examples/multi_cn/s0/run.sh
> +stage=0 # start from 0 if you need to start from data preparation
maybe add multiple machine training support here.

2021-03-15 01:48 UTC, robin1001 commented on examples/multi_cn/s0/tools
> +../../aishell/s0/tools/
../../../tools/

2021-03-15 01:49 UTC, fanlu commented
https://github.com/kaldi-asr/kaldi/pull/4433
maybe this pr is useful for speed up stcmds data prepare

2021-03-15 01:51 UTC, robin1001 requested changes
please see inline, and please also check in the result.

2021-03-15 12:52 UTC, robin1001 commented on examples/multi_cn/s0/README.md
> +* Aidatatang (140 hours)
on all open source Chinese corpus, aishell2 and TAL are not on OpenSLR.

2021-03-15 12:54 UTC, robin1001 commented on examples/multi_cn/s0/README.md
> +aishell-1 results
it's better is we list all results in just one table.

2021-03-15 12:55 UTC, robin1001 requested changes
please see inline.

2021-03-16 08:01 UTC, robin1001 approved these changes

2021-03-16 08:01 UTC, merged